-- Seed the exercises table from the working artifact's 150-entry library
-- Run once, after migrations, before first use.

insert into exercises (name, type, primary_muscle, secondary_muscle, status) values
  ('Back Squat', 'resistance', 'quads', 'glutes', 'approved'),
  ('Front Squat', 'resistance', 'quads', 'core', 'approved'),
  ('Leg Press', 'resistance', 'quads', 'glutes', 'approved'),
  ('Bulgarian Split Squat', 'resistance', 'quads', 'glutes', 'approved'),
  ('Walking Lunge', 'resistance', 'quads', 'glutes', 'approved'),
  ('Leg Extension', 'resistance', 'quads', NULL, 'approved'),
  ('Goblet Squat', 'resistance', 'quads', 'glutes', 'approved'),
  ('Hack Squat', 'resistance', 'quads', NULL, 'approved'),
  ('Step-Up', 'resistance', 'quads', 'glutes', 'approved'),
  ('Sissy Squat', 'resistance', 'quads', NULL, 'approved'),
  ('Box Jump', 'plyometric', 'quads', 'glutes', 'approved'),
  ('Broad Jump', 'plyometric', 'quads', 'hamstrings', 'approved'),
  ('Squat Jump', 'plyometric', 'quads', 'glutes', 'approved'),
  ('Depth Jump', 'plyometric', 'quads', NULL, 'approved'),
  ('Split Jump (Jumping Lunge)', 'plyometric', 'quads', 'glutes', 'approved'),
  ('Romanian Deadlift', 'resistance', 'hamstrings', 'glutes', 'approved'),
  ('Conventional Deadlift', 'resistance', 'hamstrings', 'back', 'approved'),
  ('Nordic Curl', 'resistance', 'hamstrings', NULL, 'approved'),
  ('Lying Leg Curl', 'resistance', 'hamstrings', NULL, 'approved'),
  ('Seated Leg Curl', 'resistance', 'hamstrings', NULL, 'approved'),
  ('Good Morning', 'resistance', 'hamstrings', 'glutes', 'approved'),
  ('Single-Leg RDL', 'resistance', 'hamstrings', 'glutes', 'approved'),
  ('Stability Ball Leg Curl', 'resistance', 'hamstrings', NULL, 'approved'),
  ('Trap Bar Deadlift', 'resistance', 'hamstrings', 'quads', 'approved'),
  ('Cable Pull-Through', 'resistance', 'hamstrings', 'glutes', 'approved'),
  ('Bounding', 'plyometric', 'hamstrings', 'glutes', 'approved'),
  ('Sprint Starts', 'plyometric', 'hamstrings', NULL, 'approved'),
  ('Slider Eccentric Leg Curl', 'plyometric', 'hamstrings', NULL, 'approved'),
  ('Depth Jump to Sprint', 'plyometric', 'hamstrings', NULL, 'approved'),
  ('Broad Jump to Stick', 'plyometric', 'hamstrings', 'glutes', 'approved'),
  ('Hip Thrust', 'resistance', 'glutes', NULL, 'approved'),
  ('Barbell Glute Bridge', 'resistance', 'glutes', NULL, 'approved'),
  ('Cable Kickback', 'resistance', 'glutes', NULL, 'approved'),
  ('Sumo Deadlift', 'resistance', 'glutes', 'hamstrings', 'approved'),
  ('Curtsy Lunge', 'resistance', 'glutes', 'quads', 'approved'),
  ('Heavy Step-Up', 'resistance', 'glutes', 'quads', 'approved'),
  ('Single-Leg Hip Thrust', 'resistance', 'glutes', NULL, 'approved'),
  ('Banded Lateral Walk', 'resistance', 'glutes', NULL, 'approved'),
  ('B-Stance RDL', 'resistance', 'glutes', 'hamstrings', 'approved'),
  ('Reverse Hyper', 'resistance', 'glutes', 'hamstrings', 'approved'),
  ('Lateral Bound', 'plyometric', 'glutes', NULL, 'approved'),
  ('Skater Jump', 'plyometric', 'glutes', NULL, 'approved'),
  ('Single-Leg Bound', 'plyometric', 'glutes', NULL, 'approved'),
  ('Depth Drop to Broad Jump', 'plyometric', 'glutes', NULL, 'approved'),
  ('Hurdle Hop', 'plyometric', 'glutes', NULL, 'approved'),
  ('Barbell Bench Press', 'resistance', 'chest', 'triceps', 'approved'),
  ('Incline DB Bench Press', 'resistance', 'chest', 'shoulders', 'approved'),
  ('Decline Bench Press', 'resistance', 'chest', NULL, 'approved'),
  ('DB Fly', 'resistance', 'chest', NULL, 'approved'),
  ('Cable Crossover', 'resistance', 'chest', NULL, 'approved'),
  ('Weighted Push-Up', 'resistance', 'chest', 'triceps', 'approved'),
  ('Machine Chest Press', 'resistance', 'chest', NULL, 'approved'),
  ('Dip (Chest-Focused)', 'resistance', 'chest', 'triceps', 'approved'),
  ('Pec Deck', 'resistance', 'chest', NULL, 'approved'),
  ('Landmine Press', 'resistance', 'chest', 'shoulders', 'approved'),
  ('Plyo Push-Up', 'plyometric', 'chest', 'triceps', 'approved'),
  ('Med Ball Chest Pass', 'plyometric', 'chest', NULL, 'approved'),
  ('Clap Push-Up', 'plyometric', 'chest', NULL, 'approved'),
  ('Depth Push-Up', 'plyometric', 'chest', NULL, 'approved'),
  ('Explosive Bench Throw', 'plyometric', 'chest', NULL, 'approved'),
  ('Weighted Pull-Up', 'resistance', 'back', 'biceps', 'approved'),
  ('Lat Pulldown', 'resistance', 'back', 'biceps', 'approved'),
  ('Pendlay Row', 'resistance', 'back', 'biceps', 'approved'),
  ('Chest-Supported Row', 'resistance', 'back', NULL, 'approved'),
  ('Seated Cable Row', 'resistance', 'back', 'biceps', 'approved'),
  ('T-Bar Row', 'resistance', 'back', NULL, 'approved'),
  ('Single-Arm DB Row', 'resistance', 'back', NULL, 'approved'),
  ('Deadlift (Back-Focused)', 'resistance', 'back', 'hamstrings', 'approved'),
  ('Straight-Arm Pulldown', 'resistance', 'back', NULL, 'approved'),
  ('Inverted Row', 'resistance', 'back', 'biceps', 'approved'),
  ('Med Ball Slam', 'plyometric', 'back', 'core', 'approved'),
  ('Explosive Pull-Up', 'plyometric', 'back', NULL, 'approved'),
  ('Battle Rope Slam', 'plyometric', 'back', NULL, 'approved'),
  ('Explosive Renegade Row', 'plyometric', 'back', NULL, 'approved'),
  ('Med Ball Overhead Throw', 'plyometric', 'back', 'shoulders', 'approved'),
  ('Seated DB Shoulder Press', 'resistance', 'shoulders', NULL, 'approved'),
  ('Barbell Overhead Press', 'resistance', 'shoulders', 'triceps', 'approved'),
  ('Lateral Raise', 'resistance', 'shoulders', NULL, 'approved'),
  ('Front Raise', 'resistance', 'shoulders', NULL, 'approved'),
  ('Rear Delt Fly', 'resistance', 'shoulders', NULL, 'approved'),
  ('Arnold Press', 'resistance', 'shoulders', NULL, 'approved'),
  ('Cable Lateral Raise', 'resistance', 'shoulders', NULL, 'approved'),
  ('Upright Row', 'resistance', 'shoulders', 'back', 'approved'),
  ('Face Pull', 'resistance', 'shoulders', 'back', 'approved'),
  ('Landmine Lateral Raise', 'resistance', 'shoulders', NULL, 'approved'),
  ('Med Ball Overhead Slam', 'plyometric', 'shoulders', NULL, 'approved'),
  ('Med Ball Rotational Throw', 'plyometric', 'shoulders', 'core', 'approved'),
  ('Battle Rope Wave', 'plyometric', 'shoulders', NULL, 'approved'),
  ('Explosive DB Push Press', 'plyometric', 'shoulders', NULL, 'approved'),
  ('Med Ball Chest-to-Overhead Throw', 'plyometric', 'shoulders', NULL, 'approved'),
  ('Barbell Curl', 'resistance', 'biceps', NULL, 'approved'),
  ('DB Curl', 'resistance', 'biceps', NULL, 'approved'),
  ('Hammer Curl', 'resistance', 'biceps', NULL, 'approved'),
  ('Incline DB Curl', 'resistance', 'biceps', NULL, 'approved'),
  ('Preacher Curl', 'resistance', 'biceps', NULL, 'approved'),
  ('Cable Curl', 'resistance', 'biceps', NULL, 'approved'),
  ('Concentration Curl', 'resistance', 'biceps', NULL, 'approved'),
  ('EZ-Bar Curl', 'resistance', 'biceps', NULL, 'approved'),
  ('Chin-Up (Biceps-Focused)', 'resistance', 'biceps', 'back', 'approved'),
  ('Reverse Curl', 'resistance', 'biceps', NULL, 'approved'),
  ('Explosive Barbell Curl', 'plyometric', 'biceps', NULL, 'approved'),
  ('Med Ball Bicep Toss', 'plyometric', 'biceps', NULL, 'approved'),
  ('Battle Rope Curl Wave', 'plyometric', 'biceps', NULL, 'approved'),
  ('Explosive Chin-Up', 'plyometric', 'biceps', 'back', 'approved'),
  ('Resistance Band Snap Curl', 'plyometric', 'biceps', NULL, 'approved'),
  ('Triceps Pushdown', 'resistance', 'triceps', NULL, 'approved'),
  ('Skull Crusher', 'resistance', 'triceps', NULL, 'approved'),
  ('Close-Grip Bench Press', 'resistance', 'triceps', 'chest', 'approved'),
  ('Weighted Dip', 'resistance', 'triceps', 'chest', 'approved'),
  ('Overhead Triceps Extension', 'resistance', 'triceps', NULL, 'approved'),
  ('Cable Overhead Extension', 'resistance', 'triceps', NULL, 'approved'),
  ('DB Kickback', 'resistance', 'triceps', NULL, 'approved'),
  ('JM Press', 'resistance', 'triceps', NULL, 'approved'),
  ('Rope Pushdown', 'resistance', 'triceps', NULL, 'approved'),
  ('Diamond Push-Up', 'resistance', 'triceps', 'chest', 'approved'),
  ('Plyo Diamond Push-Up', 'plyometric', 'triceps', 'chest', 'approved'),
  ('Explosive Close-Grip Push-Up', 'plyometric', 'triceps', NULL, 'approved'),
  ('Med Ball Push Throw', 'plyometric', 'triceps', 'chest', 'approved'),
  ('Battle Rope Triceps Extension', 'plyometric', 'triceps', NULL, 'approved'),
  ('Narrow Depth Push-Up', 'plyometric', 'triceps', NULL, 'approved'),
  ('Standing Calf Raise', 'resistance', 'calves', NULL, 'approved'),
  ('Seated Calf Raise', 'resistance', 'calves', NULL, 'approved'),
  ('Leg Press Calf Raise', 'resistance', 'calves', NULL, 'approved'),
  ('Single-Leg Calf Raise', 'resistance', 'calves', NULL, 'approved'),
  ('Smith Machine Calf Raise', 'resistance', 'calves', NULL, 'approved'),
  ('Donkey Calf Raise', 'resistance', 'calves', NULL, 'approved'),
  ('DB Calf Raise', 'resistance', 'calves', NULL, 'approved'),
  ('Calf Press (Machine)', 'resistance', 'calves', NULL, 'approved'),
  ('Barbell Calf Raise', 'resistance', 'calves', NULL, 'approved'),
  ('Tibia Raise', 'resistance', 'calves', NULL, 'approved'),
  ('Jump Rope', 'plyometric', 'calves', NULL, 'approved'),
  ('Pogo Hop', 'plyometric', 'calves', NULL, 'approved'),
  ('Ankle Hop', 'plyometric', 'calves', NULL, 'approved'),
  ('Depth Jump (Ankle Focus)', 'plyometric', 'calves', NULL, 'approved'),
  ('Bounding (Ankle Stiffness)', 'plyometric', 'calves', NULL, 'approved'),
  ('Cable Woodchopper', 'resistance', 'core', NULL, 'approved'),
  ('Hanging Leg Raise', 'resistance', 'core', NULL, 'approved'),
  ('Ab Wheel Rollout', 'resistance', 'core', NULL, 'approved'),
  ('Weighted Plank', 'resistance', 'core', NULL, 'approved'),
  ('Weighted Sit-Up', 'resistance', 'core', NULL, 'approved'),
  ('Pallof Press', 'resistance', 'core', NULL, 'approved'),
  ('Russian Twist', 'resistance', 'core', NULL, 'approved'),
  ('Cable Crunch', 'resistance', 'core', NULL, 'approved'),
  ('Side Plank', 'resistance', 'core', NULL, 'approved'),
  ('Dead Bug', 'resistance', 'core', NULL, 'approved'),
  ('Med Ball Rotational Slam', 'plyometric', 'core', NULL, 'approved'),
  ('Med Ball Sit-Up Throw', 'plyometric', 'core', NULL, 'approved'),
  ('Explosive V-Up', 'plyometric', 'core', NULL, 'approved'),
  ('Med Ball Side Slam', 'plyometric', 'core', NULL, 'approved'),
  ('Explosive Plank-to-Push-Up', 'plyometric', 'core', 'chest', 'approved');
